plugins {
    id 'java'
    id 'application'
}

group = 'btxds.mmide'
version = '1.0.0'

application {
    mainClass = 'btxds.mmide.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':mmide-api')

    implementation 'com.formdev:flatlaf:3.5.4'
    implementation 'com.formdev:flatlaf-intellij-themes:3.5.4'
    implementation 'com.formdev:flatlaf-extras:3.5.4'
    implementation 'com.google.code.gson:gson:2.11.0'
}

jar {
    manifest {
        attributes 'Main-Class': 'btxds.mmide.Main'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}